// Generated by `npm run contract:build` from contract/openapi.json. Do not edit.

/// The SHA-256 of the contract this build was generated from (`contract/openapi.json`): what the app keys a payload
/// it keeps across launches on, so one kept under another contract is never read.
public let contractDigest = "14bbbdd3627e798dbe2e5390c5b3a189f4567700e002f48cf4d0948668197cad"
