/**
 * Builds the presentation contract's OpenAPI document from the server's TypeScript types (D-056, SWIFTUI_REBUILD.md
 * section 4.3). `npm run contract:build` writes it to `contract/openapi.json`; the drift test builds it again and
 * compares, and validates live responses against the closed form (`{ open: false }`).
 *
 * The rules applied here:
 * - Every type exported from `server/contract/index.ts` becomes a named component, generated by ts-json-schema-generator.
 * - A closed string union (two or more values) becomes an open enum, in the shape swift-openapi-generator decodes as
 *   open: `anyOf: [{ type: string, enum: [...] }, { type: string }]`. An older app then reads a new code as a plain
 *   string instead of failing. A single string literal is a tag (an event's `type`), not a union, and stays closed.
 * - `ServerEvent`, the event stream's union, is open too: an `UnknownServerEvent` (just a `type`) is added last to its
 *   `anyOf`, so an event a newer server sends decodes, and the client ignores it.
 * - `GameDate` stays `type: string` with no format.
 * - Objects never say `additionalProperties: false`: a generated client would then reject a field added later. The
 *   drift test adds `unevaluatedProperties: false` when it validates, so the server may not send an undescribed field.
 * - Output is deterministic: components in name order, paths in path order, methods in a fixed order.
 */
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { createGenerator, type Config } from 'ts-json-schema-generator';
import { operations, type Operation } from '../../server/contract/routes.js';

type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
type Schema = { [key: string]: Json };

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
export const CONTRACT_INDEX = path.join(ROOT, 'server', 'contract', 'index.ts');
export const SPEC_PATH = path.join(ROOT, 'contract', 'openapi.json');

/** Unions a newer server may extend with a new member, and the catch-all an older client decodes such a member as. */
export const OPEN_UNIONS: Record<string, string> = { ServerEvent: 'UnknownServerEvent' };

const COMPONENT_NAME = /^[A-Za-z0-9._-]+$/;
const METHOD_ORDER = ['get', 'put', 'post', 'delete'];

/** The names `server/contract/index.ts` exports (types and interfaces, including re-exports). */
export function contractTypeNames(): string[] {
  const program = ts.createProgram([CONTRACT_INDEX], {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: true,
    skipLibCheck: true,
    noEmit: true,
    types: ['node'],
  });
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(CONTRACT_INDEX);
  const module = source && checker.getSymbolAtLocation(source);
  if (!module) throw new Error(`Could not read ${CONTRACT_INDEX}`);
  return checker.getExportsOfModule(module).map((s) => s.getName()).sort();
}

/** The schema of every exported contract type, as JSON Schema definitions keyed by type name. */
function generateDefinitions(names: string[]): Record<string, Schema> {
  const config: Config = {
    path: CONTRACT_INDEX,
    tsconfig: path.join(ROOT, 'tsconfig.json'),
    type: '*',
    expose: 'export',
    topRef: true,
    jsDoc: 'extended',
    // Never `additionalProperties: false` in the published spec (see the header)
    additionalProperties: true,
    // `npx tsc --noEmit` type-checks the server; the generator only reads the types
    skipTypeCheck: true,
    sortProps: false,
  };
  const generator = createGenerator(config);
  const definitions: Record<string, Schema> = {};
  for (const name of names) {
    const schema = generator.createSchema(name) as unknown as { definitions?: Record<string, Schema> };
    Object.assign(definitions, schema.definitions ?? {});
  }
  return definitions;
}

function isObject(value: Json | undefined): value is { [key: string]: Json } {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

const isNullSchema = (node: Json): boolean => isObject(node) && node.type === 'null' && Object.keys(node).length === 1;

/**
 * swift-openapi-generator reads `null` only as a member of `type` (`type: [string, "null"]`); a `{ type: "null" }` in an
 * `anyOf` makes it drop the whole property. So, in the published form, `X | null` is written the way it reads:
 * - an inline schema with one `type` gains `"null"` in its `type` (exact, and a Swift optional);
 * - anything else (a component reference, an open enum, a union) loses the null member and the property leaves
 *   `required`, which the generator also reads as a Swift optional: it decodes a JSON null as nil.
 * Returns the property's schema and whether it must leave `required`. The closed form keeps `X | null` exactly.
 */
function liftNull(schema: Json): { schema: Json; optional: boolean } {
  if (!isObject(schema)) return { schema, optional: false };
  const key = Array.isArray(schema.anyOf) ? 'anyOf' : Array.isArray(schema.oneOf) ? 'oneOf' : null;
  const members = key ? (schema[key] as Json[]) : [];
  if (!key || !members.some(isNullSchema)) return { schema, optional: false };
  const rest = members.filter((m) => !isNullSchema(m));
  const { [key]: _members, ...outer } = schema;
  if (rest.length > 1) return { schema: { ...outer, anyOf: rest }, optional: true };
  const only = rest[0];
  if (isObject(only) && typeof only.type === 'string' && only.$ref === undefined) {
    return { schema: { ...only, ...outer, type: [only.type, 'null'] }, optional: false };
  }
  return { schema: isObject(only) ? { ...only, ...outer } : only, optional: true };
}

/** Rewrites one schema node (recursively): component references, open enums, closed tags, and nullability. */
function transform(node: Json, open: boolean): Json {
  if (Array.isArray(node)) return node.map((n) => transform(n, open));
  if (!isObject(node)) return node;
  const out: Schema = {};
  for (const [key, value] of Object.entries(node)) {
    if (key === '$ref' && typeof value === 'string') {
      const name = decodeURIComponent(value.replace(/^#\/definitions\//, ''));
      if (!COMPONENT_NAME.test(name)) throw new Error(`Type "${name}" cannot be a component name; give it an exported name in server/contract/index.ts`);
      out.$ref = `#/components/schemas/${name}`;
    } else if (key === 'additionalProperties' && value === false) {
      // dropped: see the header
    } else {
      out[key] = transform(value, open);
    }
  }
  // A string literal is a tag and stays closed; swift-openapi-generator reads a one-value enum, not `const`
  if (typeof out.const === 'string') {
    out.enum = [out.const];
    delete out.const;
  }
  const values = out.enum;
  if (open && Array.isArray(values) && values.length > 1 && values.every((v) => typeof v === 'string' || v === null)) {
    const strings = values.filter((v): v is string => typeof v === 'string');
    const { enum: _enum, type: _type, ...rest } = out;
    // A nullable one reads null through its open member, which the generator accepts as `type: [string, "null"]`
    const other: Json = values.includes(null) ? { type: ['string', 'null'] } : { type: 'string' };
    return { ...rest, anyOf: [{ type: 'string', enum: strings }, other] };
  }
  if (open && isObject(out.properties)) {
    const optional = new Set<string>();
    for (const [name, property] of Object.entries(out.properties)) {
      const lifted = liftNull(property);
      out.properties[name] = lifted.schema;
      if (lifted.optional) optional.add(name);
    }
    if (Array.isArray(out.required) && optional.size) {
      out.required = out.required.filter((r) => typeof r !== 'string' || !optional.has(r));
      if (out.required.length === 0) delete out.required;
    }
  }
  return out;
}

/** Throws where a `{ type: "null" }` member is left in the published form (a place `liftNull` cannot reach). */
function assertNoNullMembers(node: Json, where: string): void {
  if (Array.isArray(node)) return node.forEach((n, i) => assertNoNullMembers(n, `${where}/${i}`));
  if (!isObject(node)) return;
  for (const key of ['anyOf', 'oneOf']) {
    const members = node[key];
    if (Array.isArray(members) && members.some(isNullSchema)) {
      throw new Error(`${where}: "X | null" is only supported as an object property; the Swift generator cannot read it here`);
    }
  }
  for (const [key, value] of Object.entries(node)) assertNoNullMembers(value, `${where}/${key}`);
}

function sortKeys<T>(record: Record<string, T>): Record<string, T> {
  return Object.fromEntries(Object.entries(record).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)));
}

function schemaRef(name: string): Schema {
  return { $ref: `#/components/schemas/${name}` };
}

function openApiPath(expressPath: string): string {
  return expressPath.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
}

function operationObject(op: Operation): Schema {
  const responses: Schema = {
    200: op.stream
      ? {
          description: `A stream of server-sent events; each event's data is a JSON ${op.response}.`,
          // No schema here, as swift-openapi-generator's event-stream pattern has it: the body is raw bytes, and the
          // client decodes each event's data as the named component (`asDecodedServerSentEventsWithJSONData`)
          content: { 'text/event-stream': {} },
        }
      : { description: 'OK', content: { 'application/json': { schema: schemaRef(op.response) } } },
  };
  for (const [status, type] of Object.entries(op.errors ?? {})) {
    responses[status] = { description: status === '400' ? 'The request could not be done' : `HTTP ${status}`, content: { 'application/json': { schema: schemaRef(type) } } };
  }
  const operation: Schema = {
    operationId: op.operationId,
    summary: op.summary,
    tags: [op.reused ? 'reused' : 'v2'],
  };
  if (op.params?.length) {
    operation.parameters = op.params.map((p) => ({ name: p.name, in: p.in, required: p.required, description: p.description, schema: { type: p.schema } }));
  }
  if (op.request) {
    operation.requestBody = { required: true, content: { 'application/json': { schema: schemaRef(op.request) } } };
  }
  operation.responses = responses;
  return operation;
}

export interface BuildOptions {
  /** false: enums stay closed and `ServerEvent` has no catch-all (what the drift test validates live responses with). */
  open?: boolean;
}

/** The OpenAPI 3.1 document, as a plain object. */
export function buildSpec(options: BuildOptions = {}): Schema {
  const open = options.open ?? true;
  const names = contractTypeNames();
  const definitions = generateDefinitions(names);
  const schemas: Record<string, Schema> = {};
  for (const [name, schema] of Object.entries(definitions)) {
    if (!COMPONENT_NAME.test(name)) throw new Error(`Type "${name}" cannot be a component name`);
    schemas[name] = transform(schema, open) as Schema;
    if (open) assertNoNullMembers(schemas[name], `#/components/schemas/${name}`);
  }
  for (const [union, catchAll] of Object.entries(OPEN_UNIONS)) {
    const schema = schemas[union];
    const members = schema?.anyOf ?? schema?.oneOf;
    if (!schema || !Array.isArray(members) || !schemas[catchAll]) throw new Error(`Open union ${union} or its catch-all ${catchAll} is missing`);
    delete schema.oneOf;
    schema.anyOf = open ? [...members, schemaRef(catchAll)] : members;
  }

  const paths: Record<string, Schema> = {};
  const seen = new Set<string>();
  for (const op of operations) {
    if (seen.has(op.operationId)) throw new Error(`Duplicate operationId ${op.operationId}`);
    seen.add(op.operationId);
    for (const type of [op.response, op.request, ...Object.values(op.errors ?? {})]) {
      if (type && !schemas[type]) throw new Error(`${op.operationId} names ${type}, which server/contract/index.ts does not export`);
    }
    const key = openApiPath(op.path);
    paths[key] ??= {};
    if (paths[key][op.method]) throw new Error(`${op.method.toUpperCase()} ${op.path} is listed twice`);
    paths[key][op.method] = operationObject(op);
  }
  const orderedPaths = Object.fromEntries(
    Object.entries(sortKeys(paths)).map(([p, methods]) => [
      p,
      Object.fromEntries(Object.entries(methods).sort(([a], [b]) => METHOD_ORDER.indexOf(a) - METHOD_ORDER.indexOf(b))),
    ]),
  );

  return {
    openapi: '3.1.0',
    info: {
      title: 'Pennant',
      // The contract's own version, not the app's: the app version lives only in package.json (AGENTS.md)
      version: '1',
      description:
        'The presentation contract between the Pennant server and the Mac app (D-056). Generated by `npm run contract:build` from `server/contract/`; do not edit by hand.',
    },
    security: [{ bearer: [] }],
    tags: [
      { name: 'v2', description: 'The Mac app\'s own API, under /api/v2.' },
      { name: 'reused', description: 'Routes the React app already serves, described for the Mac app.' },
    ],
    paths: orderedPaths,
    components: {
      securitySchemes: {
        bearer: { type: 'http', scheme: 'bearer', description: 'The per-launch token the app hands the sidecar on stdin.' },
      },
      schemas: sortKeys(schemas),
    },
  };
}

/** The document as committed: two-space JSON and a final newline. */
export function serializeSpec(spec: Schema): string {
  return `${JSON.stringify(spec, null, 2)}\n`;
}
