import Foundation
import Testing

/// The shapes the contract will carry before any operation serves them (`tests/contractShapes/index.ts`), generated by
/// the same pipeline: a number-or-string field (a table's sort keys, SWIFTUI_REBUILD.md section 4.1) decodes both ways
/// and as unknown, and a whole number is an `Int`.
@Suite("Contract shapes")
struct ContractShapesTests {
    private func decode<T: Decodable>(_ type: T.Type, _ json: String) throws -> T {
        try JSONDecoder().decode(type, from: Data(json.utf8))
    }

    @Test("sort keys that are numbers, strings or unknown all decode, each as what it is")
    func sortKeys() throws {
        let row = try decode(Components.Schemas.SortKeys.self, #"{"sort":{"war":2.5,"name":"Ortiz","age":null,"pos":"SS"}}"#)
        let war = try #require(row.sort.additionalProperties["war"] ?? nil)
        #expect(war.value1 == 2.5)
        #expect(war.value2 == nil)
        let name = try #require(row.sort.additionalProperties["name"] ?? nil)
        #expect(name.value2 == "Ortiz")
        #expect(name.value1 == nil)
        // Unknown is kept as unknown: present, and nil
        #expect(row.sort.additionalProperties.keys.contains("age"))
        #expect((row.sort.additionalProperties["age"] ?? nil) == nil)
    }

    @Test("a number-or-string field decodes either way, and null where it may be null")
    func mixed() throws {
        let number = try decode(Components.Schemas.Mixed.self, #"{"either":7,"eitherOrNull":"seven"}"#)
        #expect(number.either.value1 == 7)
        #expect(number.eitherOrNull?.value2 == "seven")
        let text = try decode(Components.Schemas.Mixed.self, #"{"either":"seven","eitherOrNull":null}"#)
        #expect(text.either.value2 == "seven")
        #expect(text.eitherOrNull == nil)
    }

    @Test("a whole number is an Int, and a concrete alias of a generic is one named type")
    func integers() throws {
        let row = try decode(Components.Schemas.CountedRow.self, #"{"id":"r1","item":{"id":42,"count":null}}"#)
        let id: Int = row.item.id
        #expect(id == 42)
        #expect(row.item.count == nil)
        let counted: Components.Schemas.Counted = row.item
        #expect(counted.id == 42)
    }
}
