/**
 * Every operation in the presentation contract (D-056, SWIFTUI_REBUILD.md section 4.3): what `npm run contract:build`
 * writes into `contract/openapi.json` as its paths.
 *
 * Two kinds of operation are listed:
 * - everything under `/api/v2/`, which is the Mac app's own API (the drift test fails on a `/v2` route missing here);
 * - reused routes the React app already serves and the Mac app needs, listed one by one as the milestone that first
 *   needs each is built. At N2 that is the app skeleton's (N3): the server's status and import, finding and choosing
 *   the save, data status, settings and key status, and the club list; N3 added saving the settings (the club the
 *   Setup window picks, the appearance). The staff room's chat stream and the jobs
 *   endpoints join at N13, trade analysis at N12. The rest of the legacy routes are not described.
 *
 * Types are named, never written inline: each `request`, `response` and `errors` entry names a type exported from
 * `./index.ts`, so the spec's schemas all come from the server's own TypeScript types.
 */

export type HttpMethod = 'get' | 'post' | 'put' | 'delete';

export interface OperationParam {
  name: string;
  in: 'path' | 'query';
  schema: 'string' | 'integer' | 'number' | 'boolean';
  required: boolean;
  description: string;
}

export interface Operation {
  /** Unique; becomes the Swift client's method name. */
  operationId: string;
  method: HttpMethod;
  /** The Express path, with `:name` parameters (`/api/player/:id`). */
  path: string;
  summary: string;
  params?: OperationParam[];
  /** The JSON request body's type, when the operation takes one. */
  request?: string;
  /** The 200 response's type; for a stream, the type of each event's JSON `data`. */
  response: string;
  /** Other documented responses: status code to type. */
  errors?: Record<number, string>;
  /** Server-sent events (`text/event-stream`) rather than one JSON body. */
  stream?: boolean;
  /** A route the React app already serves, described for the Mac app, rather than a new `/v2` route. */
  reused: boolean;
}

/** A club in a `/v2` path: its team id, or `automatic` for the club the app follows (configured, else the human's). */
const ORG_PARAM: OperationParam = {
  name: 'org', in: 'path', schema: 'string', required: true,
  description: 'A team id, or `automatic` for the club the app follows (the configured club, else the one the save\'s human runs).',
};

export const operations: Operation[] = [
  // ── The Mac app's own API (/api/v2) ─────────────────────────────────────
  {
    operationId: 'streamEvents',
    method: 'get',
    path: '/api/v2/events',
    summary: 'Server-sent events: a hello with the status, then import, job and fresh-export news as it happens.',
    response: 'ServerEvent',
    stream: true,
    reused: false,
  },
  {
    operationId: 'getCatalog',
    method: 'get',
    path: '/api/v2/catalog',
    summary: 'The glossary, the stat catalog, each club\'s palette, logo and record, and the departments with their heads.',
    response: 'Catalog',
    reused: false,
  },
  {
    operationId: 'getDataStatusWords',
    method: 'get',
    path: '/api/v2/data-status',
    summary: 'How current the data is, in words: the headline with its basis, each source\'s line, the dates and places.',
    response: 'DataStatusView',
    reused: false,
  },

  {
    operationId: 'getFrontOffice',
    method: 'get',
    path: '/api/v2/front-office/:org',
    summary: 'The Morning Report: its masthead (record, place, runs, last five, next game, trade deadline), the lede, "How we win and lose", the roster map, the desk (every department\'s items to decide, in a stated order) and one card per department.',
    params: [ORG_PARAM],
    response: 'FrontOfficeSummary',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getDepartmentReport',
    method: 'get',
    path: '/api/v2/departments/:org/:dept',
    summary: 'One department\'s full report: prepared by, key figures, to decide, watching, what changed, what we can\'t see.',
    params: [
      ORG_PARAM,
      { name: 'dept', in: 'path', schema: 'string', required: true, description: 'The department\'s id (`majorLeague`, `farm`, ...).' },
    ],
    response: 'DepartmentReport',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  // Farm & Development's views (N10): one path per view, each its own payload, from the club's kept build
  {
    operationId: 'getFarmOrganization',
    method: 'get',
    path: '/api/v2/views/:org/farm/organization',
    summary: 'The farm as one organization: system-wide findings, who it could reach for at each position and level, starters against rotation spots, the players past their level\'s window, and the lines the reading used.',
    params: [ORG_PARAM],
    response: 'FarmOrganizationView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFarmAffiliates',
    method: 'get',
    path: '/api/v2/views/:org/farm/affiliates',
    summary: 'The organization from the major-league club down, and each affiliate read twice: can it field a team, and are its players developing (D-045).',
    params: [ORG_PARAM],
    response: 'FarmAffiliatesView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFarmAssignments',
    method: 'get',
    path: '/api/v2/views/:org/farm/assignments',
    summary: 'Every minor leaguer\'s assignment and what the organization makes of it, in the farm\'s stated order; the stakes column has no sort key (D-050).',
    params: [ORG_PARAM],
    response: 'FarmAssignmentsView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFarmDecision',
    method: 'get',
    path: '/api/v2/views/:org/farm/decision',
    summary: 'One player\'s assignment in the order a GM decides, with what follows if he moves (a cascade that stops); read ahead for the desk\'s players and every assignment in question, else on the request.',
    // Keyed as Major League Ops' decision is (N8): the decision target's `key` as a query, the view's path its own
    params: [ORG_PARAM, { name: 'player', in: 'query', schema: 'string', required: true, description: 'The player\'s id (a farm decision target\'s `key`).' }],
    response: 'FarmDecisionView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFarmProspects',
    method: 'get',
    path: '/api/v2/views/:org/farm/prospects',
    summary: 'Player Development\'s calls: the development meetings it raises and the board of every minor leaguer, in the roster\'s order (no score orders it).',
    params: [ORG_PARAM],
    response: 'FarmProspectsView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFarmDevelopment',
    method: 'get',
    path: '/api/v2/views/:org/farm/development',
    summary: 'What our scouts have seen over this save\'s rating history (D-064), how fast it moves against comparable players, and the biggest changes.',
    params: [ORG_PARAM],
    response: 'FarmDevelopmentView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFarmDevelopmentDetail',
    method: 'get',
    path: '/api/v2/views/:org/farm/development/:playerId',
    summary: 'One player\'s scouting history in this save: each snapshot, the grades that moved, and how he compares with his peers.',
    params: [ORG_PARAM, { name: 'playerId', in: 'path', schema: 'string', required: true, description: 'The player\'s id.' }],
    response: 'FarmDevelopmentDetail',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getClaimTrail',
    method: 'get',
    path: '/api/v2/claims/:key',
    summary: 'The evidence trail behind an item, built on demand (an MLB need\'s responses); the key is the item\'s `evidence`.',
    params: [{ name: 'key', in: 'path', schema: 'string', required: true, description: 'An item\'s `evidence` key.' }],
    response: 'ClaimTrail',
    errors: { 404: 'ApiError' },
    reused: false,
  },

  // Major League Ops' views (N8): one payload per view, under the per-view endpoint
  {
    operationId: 'getMajorLeagueOverview',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/overview',
    summary: 'Major League Ops\' companion to its report: the staff\'s views at a glance, the open needs grouped as the department groups them (each opening its decision), the what-if, how the philosophy leans and what it can\'t see.',
    params: [ORG_PARAM],
    response: 'MlbOverviewView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeaguePositionPlayers',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/positionPlayers',
    summary: 'Position players: the lineup as usage shows it, each regular read on his bat, glove and running against the standard for his job, as a table with each row\'s detail.',
    params: [ORG_PARAM],
    response: 'MlbPositionPlayersView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeaguePitchingStaff',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/pitchingStaff',
    summary: 'Pitching staff: the rotation and the bullpen, each arm read against the standard for his job, and the notes on how the pen is used.',
    params: [ORG_PARAM],
    response: 'MlbPitchingStaffView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueBench',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/benchBackups',
    summary: 'Bench & Backups: what the bench is for and who does each job (never a bench score), and the bench itself.',
    params: [ORG_PARAM],
    response: 'MlbBenchView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueDecision',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/decision',
    summary: 'One need\'s decision: the problem, why it was flagged, the staff\'s call, the ways to respond followed through, every candidate and the roster mechanics. Built on its first open and kept until the next import; it ranks nobody and makes no move.',
    params: [
      ORG_PARAM,
      { name: 'need', in: 'query', schema: 'string', required: true, description: 'The need\'s id (a decision target\'s `key`), or `mlb:what_if:<playerId>`.' },
      { name: 'role', in: 'query', schema: 'string', required: false, description: 'For an open spot: the role to explore, as a served choice sends it.' },
      { name: 'context', in: 'query', schema: 'string', required: false, description: 'The assignment Player Development is asked to judge, as a served choice sends it.' },
      { name: 'days', in: 'query', schema: 'integer', required: false, description: 'For a what-if: how many days he is assumed out, as a served choice sends it.' },
    ],
    response: 'MlbDecisionView',
    errors: { 404: 'ApiError' },
    reused: false,
  },

  // Major League Ops' clubhouse tools (N9, D-069): one payload per tool, built after every import
  {
    operationId: 'getMajorLeagueLineup',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/lineup',
    summary: 'Lineup: the staff\'s card for one ask (the opposing hand, the ordering, the DH, what it is built from), with each slot\'s reason, the bench, who is out and who is not scouted. Never written to OOTP.',
    params: [
      ORG_PARAM,
      { name: 'vs', in: 'query', schema: 'string', required: false, description: 'The opposing starter\'s hand (`r` or `l`), as a served choice sends it; the next game\'s starter\'s by default.' },
      { name: 'style', in: 'query', schema: 'string', required: false, description: 'How the order is written (`saber` or `trad`), as a served choice sends it.' },
      { name: 'dh', in: 'query', schema: 'string', required: false, description: 'The designated hitter (`auto` follows the league, `on`, `off`), as a served choice sends it.' },
      { name: 'sort', in: 'query', schema: 'string', required: false, description: 'What the order is built from (`talent` or `production`), as a served choice sends it.' },
    ],
    response: 'MlbLineupView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeaguePitchingAvailability',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/pitchingAvailability',
    summary: 'Pitching Availability: the bullpen as a rest calendar (each day\'s pitches, the last three days\' load, tonight\'s availability), the rotation and the starting depth.',
    params: [ORG_PARAM],
    response: 'MlbPitchingAvailabilityView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueSchedule',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/scheduleGamePlans',
    summary: 'Schedule & Game Plans: the record, how the club has done against each opponent, and every game with its result or probable starters.',
    params: [ORG_PARAM],
    response: 'MlbScheduleView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueGamePlan',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/scheduleGamePlans/plan',
    summary: 'One game\'s plan: their starter, our card against his hand, how our hitters have fared against him and his club, and their dangerous bats. The next games\' are read ahead; another is read when opened and kept until the next import.',
    params: [ORG_PARAM, { name: 'game', in: 'query', schema: 'integer', required: true, description: 'The game\'s id (a plan\'s `query.game`), one of the club\'s games.' }],
    response: 'MlbGamePlanView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueDepthChart',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/depthChart',
    summary: 'Depth Chart: the organization\'s players at each position, club by club, deepest first by the scouts\' grade now.',
    params: [ORG_PARAM],
    response: 'MlbDepthChartView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueFortyMan',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/fortyManOptions',
    summary: '40-Man & Options: the roster counts against the limits, the running clocks and option notes, and for each player what Player Rights says can be done, with its reasons.',
    params: [ORG_PARAM],
    response: 'MlbFortyManView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueRosters',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/rosters',
    summary: 'Rosters: one of the organization\'s clubs, its hitters and pitchers with the scouts\' grades and the season\'s lines. The major league club\'s is read ahead; an affiliate\'s when opened.',
    params: [ORG_PARAM, { name: 'team', in: 'query', schema: 'integer', required: false, description: 'One of the organization\'s clubs (a served choice\'s `query.team`); the major league club by default.' }],
    response: 'MlbRostersView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMajorLeagueSeasonTrends',
    method: 'get',
    path: '/api/v2/views/:org/majorLeague/seasonTrends',
    summary: 'Season Trends: the season game by game as lines to draw (run differential, scoring, winning percentage), each with what it means.',
    params: [ORG_PARAM],
    response: 'MlbSeasonTrendsView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  // Finance's and Medical's views (N12, D-071): one path per view, each its own payload, from the club's kept build
  {
    operationId: 'getFinancePayroll',
    method: 'get',
    path: '/api/v2/views/:org/finance/payrollBudget',
    summary: 'Payroll & Budget: committed salary by season against the club\'s budget, what controlled seasons could cost beside it (never in it), who comes off the books, and every contract.',
    params: [ORG_PARAM],
    response: 'FinancePayrollView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'setFinanceBudget',
    method: 'put',
    path: '/api/v2/views/:org/finance/payrollBudget/nextSeasonBudget',
    summary: 'Sets the budget the GM expects next season (in dollars; zero clears it, so today\'s budget holds flat). A Pennant setting: nothing is written to OOTP.',
    params: [ORG_PARAM],
    request: 'FinanceBudgetUpdate',
    response: 'FinanceBudgetChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFinanceContracts',
    method: 'get',
    path: '/api/v2/views/:org/finance/contracts',
    summary: 'Contracts: what each deal costs, how long the club controls him and what he\'s worth, with the club\'s figures and the groups after this season.',
    params: [ORG_PARAM],
    response: 'FinanceContractsView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFinanceFreeAgents',
    method: 'get',
    path: '/api/v2/views/:org/finance/freeAgents',
    summary: 'Free Agents: who is available now, who reaches the market after this season and who might, each with his production and a season of it at the market.',
    params: [ORG_PARAM],
    response: 'FinanceFreeAgentsView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFinanceFreeAgent',
    method: 'get',
    path: '/api/v2/views/:org/finance/freeAgents/players/:player',
    summary: 'One listed free agent\'s detail, served when the GM chooses his row: his facts, and the claims beneath the table (a season at the market, why he might reach it), each with its basis.',
    params: [ORG_PARAM, { name: 'player', in: 'path', schema: 'string', required: true, description: 'The player\'s id.' }],
    response: 'FinanceFreeAgentDetail',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFinanceHorizon',
    method: 'get',
    path: '/api/v2/views/:org/finance/horizonBoard',
    summary: 'The Horizon Board: who the club controls at each position over the next three seasons and how, the farm\'s next men never placed in a season, and committed salary against the budget.',
    params: [ORG_PARAM],
    response: 'FinanceHorizonView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getMedicalInjuryReport',
    method: 'get',
    path: '/api/v2/views/:org/medical/injuryReport',
    summary: 'The Injury Report: every injured player in the organization, majors to rookie ball, with when he is due back.',
    params: [ORG_PARAM],
    response: 'MedicalInjuryReportView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  // League Office's and Scouting's views (N12 Track B, D-072): one payload per view, built after every import
  {
    operationId: 'getLeagueStandings',
    method: 'get',
    path: '/api/v2/views/:org/league/standings',
    summary: 'Standings: every division as a table (record, games back, runs, streak, pace, magic number), our club\'s place in the race as facts, and the staff\'s rough read of the season (the postseason odds and the deadline posture, D-060: only here, with their basis).',
    params: [ORG_PARAM],
    response: 'LeagueStandingsView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getLeagueLeaders',
    method: 'get',
    path: '/api/v2/views/:org/league/leaders',
    summary: 'Leaders: the league\'s top ten in each batting and pitching category this season, with who qualifies for a rate.',
    params: [ORG_PARAM],
    response: 'LeagueLeadersView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getLeagueOrgComparison',
    method: 'get',
    path: '/api/v2/views/:org/league/orgComparison',
    summary: 'Org Comparison: every major league club of the league side by side (the roster\'s and the farm\'s expected wins, contract value, payroll and budget), each a range with its basis.',
    params: [ORG_PARAM],
    response: 'LeagueOrgComparisonView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getLeagueFranchiseHistory',
    method: 'get',
    path: '/api/v2/views/:org/league/franchiseHistory',
    summary: 'Franchise History: every season the club has played (the record chart, the season by season table, the best and worst seasons, titles) and the GM\'s own seasons.',
    params: [ORG_PARAM],
    response: 'LeagueFranchiseView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getLeagueUsVsThem',
    method: 'get',
    path: '/api/v2/views/:org/league/usVsThem',
    summary: 'Us vs Them: our club beside another, as facts (the season, at the plate, on the mound, with each club\'s league place) and their meetings this season. No odds, no posture, no verdict.',
    params: [ORG_PARAM, { name: 'team', in: 'query', schema: 'integer', required: false, description: 'The club to set beside ours (a served choice\'s `value`); the next opponent by default.' }],
    response: 'LeagueUsVsThemView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getScoutingDraftBoard',
    method: 'get',
    path: '/api/v2/views/:org/scouting/draftBoard',
    summary: 'Draft Board: once OOTP publishes the class, the staff\'s board in a stated order (our scouts\' grades now and ceiling, each with the OSA mark where it applies), its short lists and filters; before then, one sentence and the calendar. The top 300 at first; a filter or `all` serves every prospect it keeps.',
    params: [
      ORG_PARAM,
      { name: 'position', in: 'query', schema: 'string', required: false, description: 'A position group\'s key, as served (`filters[].choices[].value`); every position by default.' },
      { name: 'school', in: 'query', schema: 'string', required: false, description: 'High school or college, by its served key; both by default.' },
      { name: 'all', in: 'query', schema: 'string', required: false, description: '`1` serves every prospect on the board, not only its top 300.' },
    ],
    response: 'ScoutingDraftBoardView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getScoutingDraftProspect',
    method: 'get',
    path: '/api/v2/views/:org/scouting/draftBoard/prospects/:player',
    summary: 'A prospect\'s reasons for the staff\'s read on the Draft Board, read when he is chosen: his board row\'s detail.',
    params: [ORG_PARAM, { name: 'player', in: 'path', schema: 'integer', required: true, description: 'The prospect\'s player id.' }],
    response: 'ScoutingProspectView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getScoutingPlayerSearch',
    method: 'get',
    path: '/api/v2/views/:org/scouting/playerSearch',
    summary: 'Player Search: players by name and by tokens (position, level, club, age, hands, free agents, batters or pitchers), with their season lines; every token on offer is served.',
    params: [
      ORG_PARAM,
      { name: 'q', in: 'query', schema: 'string', required: false, description: 'Words of a player\'s name, matched as the palette\'s search matches them.' },
      { name: 'tokens', in: 'query', schema: 'string', required: false, description: 'The chosen tokens\' ids, comma-separated, as served (`kinds[].tokens[].id`).' },
      { name: 'sort', in: 'query', schema: 'string', required: false, description: 'A sortable served column\'s id: every match is sorted by it, not only the page shown. The most playing time first by default.' },
      { name: 'dir', in: 'query', schema: 'string', required: false, description: '`asc` or `desc` (the default).' },
      { name: 'offset', in: 'query', schema: 'integer', required: false, description: 'Where the page starts, as served in `more.value`; 0 by default.' },
    ],
    response: 'ScoutingPlayerSearchView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getDesk',
    method: 'get',
    path: '/api/v2/desk/:org',
    summary: 'The GM\'s desk: every item to decide with its status (open, reviewed, deferred, handled in OOTP), in the stated order, and the items set aside. A status records attention only.',
    params: [ORG_PARAM],
    response: 'DeskView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'setDeskStatus',
    method: 'put',
    path: '/api/v2/desk/:org',
    summary: 'Marks an item open, reviewed, deferred until a game date, or handled in OOTP (and keeps a note). Answers with the status it replaced and the request that undoes it. Nothing is written to OOTP.',
    params: [ORG_PARAM],
    request: 'DeskUpdate',
    response: 'DeskChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getFollowing',
    method: 'get',
    path: '/api/v2/following',
    summary: 'The clubs and players the GM follows in this save (the watchlist copied in, with its notes), and the division rivals suggested.',
    response: 'Following',
    reused: false,
  },
  {
    operationId: 'follow',
    method: 'put',
    path: '/api/v2/following',
    summary: 'Follows a club or a player, or changes a follow\'s note; answers with the request that undoes it.',
    request: 'FollowUpdate',
    response: 'FollowChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'unfollow',
    method: 'delete',
    path: '/api/v2/following',
    summary: 'Stops following a club or a player; answers with the request that undoes it.',
    params: [
      { name: 'kind', in: 'query', schema: 'string', required: true, description: '`club` or `player`.' },
      { name: 'id', in: 'query', schema: 'integer', required: true, description: 'The team id or the player id.' },
    ],
    response: 'FollowChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getWire',
    method: 'get',
    path: '/api/v2/wire/:org',
    summary: 'Around the league: moves (in the transaction log\'s own words), trades, injuries, streaks, awards, standings and news, since the last export unless asked, in the stated order (followed first when asked, then newest, then kind).',
    params: [
      ORG_PARAM,
      { name: 'since', in: 'query', schema: 'string', required: false, description: 'A game date (`2040-5-1`), or `season`; the last export\'s day when left out.' },
      { name: 'club', in: 'query', schema: 'integer', required: false, description: 'Only entries naming this club (a team id).' },
      { name: 'kind', in: 'query', schema: 'string', required: false, description: '`move`, `trade`, `injury`, `streak`, `award`, `standings` or `news`.' },
      { name: 'followed', in: 'query', schema: 'string', required: false, description: '`first` puts followed clubs and players first; `only` keeps only them.' },
    ],
    response: 'Wire',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getClubReport',
    method: 'get',
    path: '/api/v2/club/:teamId',
    summary: 'Another club\'s report under our scouting: its masthead, how it wins and loses, its roster map, its recent moves, injuries, record against us and next series with us.',
    params: [{ name: 'teamId', in: 'path', schema: 'string', required: true, description: 'A team id (or `automatic` for the club the app follows).' }],
    response: 'ClubReport',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'search',
    method: 'get',
    path: '/api/v2/search',
    summary: 'Players (ours and the league\'s), clubs and views matching every word typed, each with where it opens; followed first, then a stated order.',
    params: [{ name: 'q', in: 'query', schema: 'string', required: false, description: 'What was typed.' }],
    response: 'SearchAnswer',
    reused: false,
  },

  // ── The player window and Compare (N11) ──────────────────────────────────
  {
    operationId: 'getPlayerDossier',
    method: 'get',
    path: '/api/v2/player/:id',
    summary: 'One player\'s dossier in sections (header, overview, ratings, value, contract and rights, history), read for a club; our club\'s players read ahead after each import, any other on his first open, kept until the next import.',
    params: [
      { name: 'id', in: 'path', schema: 'integer', required: true, description: 'The player\'s id.' },
      { name: 'org', in: 'query', schema: 'string', required: false, description: 'A team id, or `automatic` (the default) for the club the app follows.' },
    ],
    response: 'PlayerDossierView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getPlayerNotes',
    method: 'get',
    path: '/api/v2/player/:id/notes',
    summary: 'The GM\'s note on a player (kept on his follow, as typed) and the notes the staff filed on him.',
    params: [{ name: 'id', in: 'path', schema: 'integer', required: true, description: 'The player\'s id.' }],
    response: 'PlayerNotesView',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'setPlayerNote',
    method: 'put',
    path: '/api/v2/player/:id/notes',
    summary: 'Sets the GM\'s note as typed (an empty note clears it); a note on a player he doesn\'t follow follows him. Answers with the request that undoes it.',
    params: [{ name: 'id', in: 'path', schema: 'integer', required: true, description: 'The player\'s id.' }],
    request: 'PlayerNoteUpdate',
    response: 'PlayerNoteChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'undoFirstPlayerNote',
    method: 'delete',
    path: '/api/v2/player/:id/notes',
    summary: 'The undo of a first note: stops following the player the note followed, the note with him.',
    params: [{ name: 'id', in: 'path', schema: 'integer', required: true, description: 'The player\'s id.' }],
    response: 'PlayerNoteChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'restoreStaffNote',
    method: 'post',
    path: '/api/v2/player/:id/staff-notes',
    summary: 'Puts a removed staff note back as it was filed (the undo of a removal).',
    params: [{ name: 'id', in: 'path', schema: 'integer', required: true, description: 'The player\'s id.' }],
    request: 'StaffNoteRestore',
    response: 'StaffNoteChange',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'removeStaffNote',
    method: 'delete',
    path: '/api/v2/player/:id/staff-notes/:noteId',
    summary: 'Removes a staff note on a player; answers with the note as filed, to put it back.',
    params: [
      { name: 'id', in: 'path', schema: 'integer', required: true, description: 'The player\'s id.' },
      { name: 'noteId', in: 'path', schema: 'integer', required: true, description: 'The note\'s id.' },
    ],
    response: 'StaffNoteChange',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getPlayerCompare',
    method: 'get',
    path: '/api/v2/compare',
    summary: 'Two to four players side by side, each figure as his own dossier serves it; ranges compared only by overlap, no verdict or combined score.',
    params: [
      { name: 'players', in: 'query', schema: 'string', required: true, description: 'Two to four player ids, comma-separated.' },
      { name: 'org', in: 'query', schema: 'string', required: false, description: 'A team id, or `automatic` (the default).' },
    ],
    response: 'PlayerCompareView',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },

  {
    operationId: 'getThemeChoices',
    method: 'get',
    path: '/api/v2/theme-packs/:org',
    summary: 'The themes a club can wear: its own colours (from the save) and each installed theme pack that fits it, with every appearance resolved; the packs refused, and why.',
    params: [ORG_PARAM],
    response: 'ThemeChoices',
    errors: { 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'chooseTheme',
    method: 'post',
    path: '/api/v2/theme-packs/:org',
    summary: 'Chooses the theme a club wears (`club-colors` for its own colours). A pack not installed, refused, or made for another club is refused (400).',
    params: [ORG_PARAM],
    request: 'ThemeChoice',
    response: 'ThemeChoices',
    errors: { 400: 'ApiError', 404: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getRatingHistory',
    method: 'get',
    path: '/api/v2/rating-history',
    summary: 'This save\'s rating history: whether some of it isn\'t used or it started fresh; the questions to ask (an earlier save whose folder has gone, or this folder\'s own history set aside); every other history the GM may carry over; and the carry-overs in force, each undoable.',
    response: 'RatingHistoryView',
    reused: false,
  },
  {
    operationId: 'answerRatingHistoryOffer',
    method: 'post',
    path: '/api/v2/rating-history/choice',
    summary: 'The GM\'s answer: carry a history over into this save (`adopt`, a question or a listed history), keep them apart (`fresh`, a question only), or undo a carry-over (`undo`). An answer that no longer fits, or names another save, is refused (400).',
    request: 'RatingHistoryChoice',
    response: 'RatingHistoryView',
    errors: { 400: 'ApiError' },
    reused: false,
  },
  {
    operationId: 'getSaveDiscovery',
    method: 'get',
    path: '/api/v2/saves',
    summary: 'The saves on this Mac, most recently played first, and the one you\'re playing when it clearly stands out, or why none does.',
    response: 'SaveDiscovery',
    reused: false,
  },
  {
    operationId: 'setUpAutomatically',
    method: 'post',
    path: '/api/v2/setup/automatic',
    summary: 'On a first run, choose and import the save that clearly stands out (and its club, when the save names one), or say why not.',
    response: 'AutomaticSetup',
    reused: false,
  },

  // ── Status and import (reused) ──────────────────────────────────────────
  {
    operationId: 'getStatus',
    method: 'get',
    path: '/api/status',
    summary: 'The save, the last import, a running import and a fresh export waiting.',
    response: 'ServerStatus',
    reused: true,
  },
  {
    operationId: 'startImport',
    method: 'post',
    path: '/api/import',
    summary: 'Import the configured save\'s export again; progress arrives on the event stream. Refused (409) while an import runs.',
    response: 'ImportAccepted',
    errors: { 400: 'ApiError', 409: 'ApiError' },
    reused: true,
  },

  // ── Setup: finding and choosing the save (reused) ───────────────────────
  {
    operationId: 'listSaves',
    method: 'get',
    path: '/api/saves',
    summary: 'The OOTP saves found in the usual places on this Mac.',
    response: 'SaveList',
    reused: true,
  },
  {
    operationId: 'getSearchLocations',
    method: 'get',
    path: '/api/search-locations',
    summary: 'Where the server looked for saves, so an empty search can say why.',
    response: 'SearchLocations',
    reused: true,
  },
  {
    operationId: 'resolveFolder',
    method: 'post',
    path: '/api/resolve-folder',
    summary: 'Check a folder the user picked: a CSV export, a save, or a folder of saves.',
    request: 'ResolveFolderRequest',
    response: 'ResolveResult',
    errors: { 400: 'ResolveResult' },
    reused: true,
  },
  {
    operationId: 'setSave',
    method: 'post',
    path: '/api/config',
    summary: 'Use this save\'s export folder, and import it (or say why the import did not start). Refused (409) while an import runs.',
    request: 'ConfigRequest',
    response: 'ConfigAccepted',
    errors: { 400: 'ApiError', 409: 'ApiError' },
    reused: true,
  },

  // ── Settings: data status, keys, the club (reused) ──────────────────────
  {
    operationId: 'getDataStatus',
    method: 'get',
    path: '/api/data-status',
    summary: 'How current the save, the export and the transaction log are, and where each was found.',
    response: 'DataStatus',
    reused: true,
  },
  {
    operationId: 'setSaveSource',
    method: 'post',
    path: '/api/save-source',
    summary: 'Name the save folder by hand when it cannot be found from the export; empty returns to automatic.',
    request: 'SaveSourceRequest',
    response: 'SaveSourceResult',
    errors: { 400: 'ApiError' },
    reused: true,
  },
  {
    operationId: 'getSettings',
    method: 'get',
    path: '/api/settings',
    summary: 'The preferences, the active provider\'s key state, the data folder and the current club.',
    response: 'SettingsResponse',
    reused: true,
  },
  {
    operationId: 'saveSettings',
    method: 'post',
    path: '/api/settings',
    summary: 'Change preferences (the club, the appearance, ...); a field left out keeps its value.',
    request: 'SettingsUpdate',
    response: 'SettingsSaved',
    reused: true,
  },
  {
    operationId: 'getProviders',
    method: 'get',
    path: '/api/settings/providers',
    summary: 'The AI providers on offer and every provider\'s key state.',
    response: 'ProvidersResponse',
    reused: true,
  },
  {
    operationId: 'listOrgs',
    method: 'get',
    path: '/api/orgs',
    summary: 'The major-league clubs, the one the save manages flagged, with their colours.',
    response: 'OrgList',
    reused: true,
  },
];
